cookie_password = "SP_Soluciones_Proyectos_Secure_Key_2026_JoanGZ"

SHEET_ID = "1pueSIWQF7FApYNMpZiQEIX25rMlSZdSCFnZTml2YKhU"

[gcp_service_account]

type = "service_account"
project_id = "civic-boulder-496515-v2"
private_key_id = "TU_PRIVATE_KEY_ID"

private_key = "TU_PRIVATE_KEY_COMPLETA"

client_email = "streamlit-gsheets@civic-boulder-496515-v2.iam.gserviceaccount.com"

client_id = "104162708315410002900"

auth_uri = "https://accounts.google.com/o/oauth2/auth"

token_uri = "https://oauth2.googleapis.com/token"

auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"

client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-gsheets%40civic-boulder-496515-v2.iam.gserviceaccount.com"